#!/bin/bash

# Your two home Wi-Fi network name
home_network1="<yourHomeWifiName>""

# The app path (adjust if necessary)
app_path="/Applications/<nameOfTheAppYouWantToOpen>"

# Get the current SSID
current_ssid=$(networksetup -getairportnetwork en0 | awk -F ": " '{print $2}')

# Check if you're connected to either of the two home networks
if [[ "$current_ssid" == "$home_network1" ]]; then
    # If at home, open your desired app
    if ! pgrep -x "NAMEOFYOURAPP" > /dev/null; then
        open "$app_path"
        echo "Opening App..."
    else
        echo "App is already running."
    fi
else
    # If not at home, close  app
    if pgrep -x "NAMEOFYOURAPP" > /dev/null; then
        pkill -x "NAMEOFYOURAPP"
        echo "Closing App..."
    else
        echo "App is not running."
    fi
fi
