#!/bin/bash

# Your two home Wi-Fi network name
home_network1="yourHomeWifiName""

# The app path (adjust if necessary)
app_path="/Applications/nameOfTheAppYouWantToOpen"

# Get the current SSID
current_ssid=$(networksetup -getairportnetwork en0 | awk -F ": " '{print $2}')

# Check if you're connected to either of the two home networks
if [[ "$current_ssid" == "$home_network1" ]]; then
    # If at home, open your desired app
    if ! pgrep -x "NAMEOFYOURAPP" > /dev/null; then
        open "$app_path"
        echo "Opening DisplayLink Manager..."
    else
        echo "DisplayLink Manager is already running."
    fi
else
    # If not at home, close DisplayLink Manager app
    if pgrep -x "DisplayLink Manager" > /dev/null; then
        pkill -x "DisplayLink Manager"
        echo "Closing DisplayLink Manager..."
    else
        echo "DisplayLink Manager is not running."
    fi
fi
